### ISSUE TITLE
Configure Virtual Machine  Instance to support access from physical host

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#105]
Issue #87 identifies need for this.

Here are the working instructions. To be tested then added to wiki 

- Go to VBox Settings. Make sure Guest machine is not running.

- Go to Network settings, Adapter 1, should be NAT - no other Adapter is needed.

- Go to Advanced and ensure Cable Connected box is checked.

- Go to Port Forwarding on same page

- Add two Rules  - UDP and TCP Protocols. Leave Host and Guest IP blank. Put 8080 in all 4 Host and Guest Port settings.

- Click OK and start machine

- From your Host MAC/PC you should be able to do localhost:8080/EFD_v2

**Comment by daiClegg** [comment]
Tested ok.

Is there any dependency on physical host proxy settings? 
On OSX i tested with & without auto-discovery of proxy and with *.local as bypass
No problems encountered.

Tested with (wifi)  and without any networking enabled for the physical host.
No problems encountered.

Should i test any other combinatios on OSX

Not tested on any other OS.

**Comment by dbrownukk** [comment]
VBox should be operating system agnostic, but we know better - I have tested on Windows 10 and works very well - 8Gb Ram, i3 chip and SSD disk

The setup instructions for port forwarding should not be needed as they can be baked into the virtual machine. There is also a commandline VirtualBox manager that can script a vbox machine startup. So we should be able to simplify further the relatively simple process...

Note - VirtualBox and Docker are incompatible on Windows 10 - need to disable windows Hyper V using 'Windows Features' which docker insists on enabling...

leaving task open to build a simple way of dsitributing and starting the virtual machine - and keeping it in synch with main version

**Comment by daiClegg** [comment]
> The setup instructions for port forwarding should not be needed as they can be baked into the virtual machine. There is also a command line VirtualBox manager that can script a vbox machine startup. So we should be able to simplify further the relatively simple process...

I hoped that would we the case; I have put the instructions for the current (only slightly demanding setup in order to get independent testing until we have the finally configured version, and that's a bit of a waste of effort until we have a stable release for Milestone 3.

**Comment by dbrownukk** [comment]
Dai,
Managed to get a drop down list in the generated spreadsheet to improve validation - attached
Probably should meetup once you have the spreadsheet format 'fixed' to work through the individual sheets..
enjoy the weekend.  Radio 5 Sports Extra makes good listening today.
David 




    On Thursday, 31 May 2018, 15:09:45 BST, dai clegg <notifications@github.com> wrote:  
 
 

The setup instructions for port forwarding should not be needed as they can be baked into the virtual machine. There is also a command line VirtualBox manager that can script a vbox machine startup. So we should be able to simplify further the relatively simple process...


I hoped that would we the case; I have put the instructions for the current (only slightly demanding setup in order to get independent testing until we have the finally configured version, and that's a bit of a waste of effort until we have a stable release for Milestone 3.

**Comment by daiClegg** [comment]
Leaving open pending testing on more platforms.
Tested ok on OS X & Windows 10

**Comment by daiClegg** [comment]
To be retested on M3 (reports);
Windows 10 nod recent OSX are acceptable platforms.

**Comment by daiClegg** [comment]
This is now pre-configured in the remote user VM image.
Tested ok.
