### ISSUE TITLE
Generate new V1 Template Interview Spreadsheet 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#108]
Generate New V1 Interview Template Spreadsheet

**Comment by dbrownukk** [comment]
Created new template generator as per latest template

Drop downs for each type and Units
Validation that if a number is required then a number is entered

Room for more validation, lets make a list and I can do in one go. 

Do we release this for testing? - clearly this will not be parseable until new parser is written

2.5 days and 15 Sheets...

**Comment by daiClegg** [comment]
Can be released for testing; anyone who wants to test load/parse of old version can use one of the many test sheets in the old format. Meanwhile, i want to test this one, because the sample has some interesting values (Acre & Acres as units 0on Land tab, but nly Acre & Hectare in the drop down. Likewise unitt (sic) for Eggs on the Livestock Product tab, but only Item, KG and CWT Bag in the dropdown.
Maybe some others?

**Comment by dbrownukk** [comment]
Deployed on idaps EFD_v2 .  (v3 undeployed)

Resource Types are set in stone as they are used to query template items for the WealthGroup and hard coded. We chose not create a more generic template....

**Comment by daiClegg** [comment]
Project: Karamoja - Central Sorghum and Livestock 1/6/14
District: Nap[ak
SubDistrict: Lobey
WG: Poor

I added multiple resources in various categories for this WG, including 'Bicycle' as 'Other Tradable Good'.
Generated the spreadsheet successfully.
No reference to Bicycle in the "Assets - Other Tradable' tab where i had expected it to appear.
Only reference to "Bicycle'' in the spreadsheet is on the Validation tab.

**Comment by dbrownukk** [comment]
Other Tradeable Goods was looking for 'OtherTradeableGoods' - fixed

**Comment by daiClegg** [comment]
Tested ok and all other characteristic resources.

**Comment by daiClegg** [comment]
related bug is issue #118
