### ISSUE TITLE
Load, Parse and ValidateNew V1 WG Interview Spreadsheet into WG Interview dataset

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#109]
Will require examination of intersection entities for resource type and loading of example data to check parse and validation + Parse and Insert of spreadsheet data

**Comment by daiClegg** [comment]
Was stalled by #116; will work around by using an existing project.

**Comment by daiClegg** [comment]
Comments  & Questions from David on deployed status:

>>> Dai's responses (on testing) inline)


Stella's spreadsheet data, as it stands will not parse all assets. This is because the Employment Unit of Work has been entered wrongly as a number - it should be a unit - day, month etc. However, the rest of the spreadsheet is parsed and you get a warning about the type of asset that is not parsed correctly and a warning for each row. However the successful sheets are parsed and the WGI is set to 'Parsed'. You can reset to 'Uploaded' and parse a corrected spreadsheet.

>>>  Parse presents multiple warnings and this error message
>>>        "Incomplete Spreadsheet data 'Interview Number' is empty"
>>> But interview number is incliuded in the spreadsheet (22)

>>> Repeated Warning messge:
>>>        "Problem parsing Employee worksheet"
>>> Should be "Problem parsing Employment worksheet"

Alternatively we could just fail the parse - I kind of like the gentle parse - for discussion.

>>> I prefer the gentle (forgiving ) parse, but we probably need to allow user to add in resources in the UI, cos if they have to go back to the spreadsheet and correct the data and re-parse, the original parse is lost anyway, so there's no value in the gentle parse?


Note that any parse deletes any existing work on the assets, thus if numbers or resource type have been set a new parse will clear things out.

Now we need to look at all the Resource Sub Types list to improve the validation. 

>>> agree - wip.

Should the Resource Type validation drop down restrict to applicable resource sub types? 

>>> yes, i think so, but in some places (e.g. Food Purchases) the lines might be Crops, Wild Foods, Livestock Products, so we need to be careful

Do I need to set the Resource Sub Type for Cash Assets to a Currency drop down??

>>> yes.

**Comment by daiClegg** [comment]
Leaving this open as i work through the issues, being posted separately
