### ISSUE TITLE
Check Synonym validation in validation run 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#151]

**Comment by daiClegg** [comment]
If we enforce the rule that synonyms must have the same KCal value, then validation should not need to consider Synonyms.

The alternative scenario might be that in the charts all synonyms of the same food type would be show as the base - otherwise we might have Matoke & Matooke in the same chart, which would be deceptive.
If we want that, then Validate might be the place to substitute the base food type name for the entered synonym. Or it could be done at parse time.
Either way this is an enhancement. Let's discuss and re-structure the issue accordingly.

**Comment by daiClegg** [comment]
As discussed: 

don't offer synonyms in the drop downs inWGI resource tabs.
match to base resource if a synonym is found in parse

**Comment by daiClegg** [comment]
If a spreadsheet includes a synonym, Parse matches with the base RST, right?

**Comment by dbrownukk** [comment]
On spreadsheet parse in WGI, if synonym is found then set the Asset/Resource type to the base RST i.e.

Crop Type entered as Tangawizi in spreadsheet

The spreadsheet parse finds that RST Tangawizi has a synonym 'Ginger'

Ginger is then added as RST for this Asset/Resource

The KCal value for Ginger is then used.

Question - Should KCal be set to null/readonly when a synonym is set?

**Comment by dbrownukk** [comment]
RST KCal value now set to 0 if RST has a Synonym identified.

**Comment by daiClegg** [comment]
Tested ok.
