### ISSUE TITLE
Food Consumed Chart - Add Resource Type to Legend

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#152]

**Comment by dbrownukk** [comment]
Fixed 

To be deployed

**Comment by daiClegg** [comment]
Is it possible to sort the legend entries by Resource type (all the Crops together, etc)?

**Comment by dbrownukk** [comment]
Yes, will order by RT in the legend  - next push to server..

**Comment by daiClegg** [comment]
That's  Resource Type right across all the WGs, not within WG.
I think that should be the sort order for the legend on all charts that list resources

**Comment by dbrownukk** [comment]
Legend is now grouped by RT, as are the bar chart rows on all charts

**Comment by daiClegg** [comment]
Tested today (31/8) Sorting appears to be by RT within WG, not across all WGs.
I had expected all Crops consumed in any WG , all Wild Foods etc.

See attached:

[WealthGroupInterview-report_20180831_1149.pdf](https://github.com/dbrownukk/EFD_v2/files/2339950/WealthGroupInterview-report_20180831_1149.pdf)

**Comment by dbrownukk** [comment]
All charts now have sorting by RT and RST not WG

They also have Wealthgroups on X axis sorted by Wealthgroup Order integer entered at the Community stage. 

deployed

**Comment by daiClegg** [comment]
Report is not including Food Purchases 
See:
Project:Mukono New Test
LZ: Banana Coffee Piggery 
District: Mukono 
Sub District: Ntenjeru 
WG: Middle

There are multiple food purchases but they do not seem to be represented.
I checked the RSTs have valid KCals.

Food consumed comes from the Crops. LS products & Wild Foods that are not sold 
Plus Food Purchases 
Plus Food Transfers & Employment that are paid in food. In both these cases the food type is specified.
Note this means that validate should check that the Food type for Transfers and for Employment, if specified is a valid Crop, WildFood, Pood Purchase or Livestock Product type 
Will enter an issue for that.
And where an employment or transfer is in food or part in food, it is the Food type, not the employment or transfer type, that should appear in the legend.

Employments and Transfers that are not paid in food should not be included in the legend (since they don't contribute to the chart).

**Comment by daiClegg** [comment]
The sort order for the WGS is the Order value on the WG record as set up in the Community module.

See Project: Mukono - New Test
LZ: Banana Coffee Piggery 
District: Mukono 
sub District: Ntenjeru

**Comment by dbrownukk** [comment]
Order now by WGOrder, RT, RST

**Comment by daiClegg** [comment]
Tested ok as described.

I would prefer grouping by RT in the legend; but if it's not an option, then we'll  do without
