### ISSUE TITLE
Entered Unit in WGI should be used during Parse to mark asset/resource as Valid/Invalid

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#160]
Somehow I missed this out as a new issue or cannot find it! Point me at the issue if this is a duplicate...

On parse of spreadsheet the Entered Unit should be validated against the RST unit. If valid then mark as valid. It is now. 

Also, WGI now displays the RST Type and Unit in the drop down making it easier to validate unit

**Comment by daiClegg** [comment]
Works very well - but should be case insensitive (Kg does not match kg).

Also shows the unit in the drop down so the user can see why the validation has failed.
That's good.

But an issue arises for Employment - e.g. enter weekly employment & pay per week. 
And the RST says the unit is daily.
See 
Project: Mukonu - New Test
LZ: Banana Coffee Piggery 
District: Mukono 
Sub District: Namakwa 
WG: Better Off

In this case, we don't care what they entered as long as they got it right in the real world.
And we cannot validate whether they did get that right, any more than that they entered the correct value for the Kgs of Maize.

So maybe we don't validate Employment types?  Or even don't store a unit for Employment
Maybe just validate that it is day, week, month or year?

Thoughts? should we discuss?

**Comment by daiClegg** [comment]
fuzzy matching (e.g. Acre & Acres) to suggest a correction, but still marked invalid would be good, if not expensive

**Comment by daiClegg** [comment]
Tested ok. This works as tested.
There may be UX issues. For instance if an Employment type has unit Day and the interviewer enters the unit  (And payment as Month, it correctly fails validation.
But what is the user to do at this point?
If they just mark it as Valid the calculation will work fine in reports, (they entered Month and entered the amount paid for a Month and the number of Months worked)
Do we just want them to change it to Valid to make sure there is no data entry error and allow any such consistent unit use?
I think so, so will close this.
Since there are such cases in the Mukono data, this will turn up in user testing so we'll get our feedback then,
