### ISSUE TITLE
Unable to create new Configuration Question

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#255]
Instance:         EFD_HM
User:               OIHM ( also tested Admin)
Background:   I want to generate a test spreadsheet with questions at all levels in order to test upload.

Steps to reproduce:
- Invoke Configuration Question Module.
- Click New
- Error message: 
> Impossible to execute New action: null

 

![image.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/67056f0a-6259-420b-ae24-33ce42f5231e)

**Comment by daiClegg** [comment]
I discovered that ConfigQuerstion was not in the oihm_user role, so i added it.
user oihm has that role.
but it made no difference.

so i have removed that module from the role, in case there s some other more arcane reason it wasn; there in the first place.

**Comment by dbrownukk** [comment]
Questions and Question Use are created from Study. 

The issue is that you are not in the context of a study. I can add a popup to select a Study but removed the Study LOV and replaced with a read-only Study field when accessing Question usages from Study. Can code around that or remove Question/Use/Answer from extras folder

**Comment by daiClegg** [comment]
I agree.  Do as much as possible fro Sudy menu. I was just being dim.

Will explore the correct workflow

**Comment by daiClegg** [comment]
Works correctly, as described and more intuitively in the appropriate workflow.
