### ISSUE TITLE
OIHM - Should a Study+Ref Year be closed to new questions once the Template spreadsheet is generated?

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#257]
You can currently add more config questions to a Study, even though the template spreadsheet has been generated, filled in and imported as a Household. 

Just looks wrong seeing a Household with different questions to the Study associated with it.

**Comment by daiClegg** [comment]
Tricky this.

It's conceivable that a user forgets to include all the questions they need before charging off to do the first interview.
Also, it's conceivable that a user might realise after a few interviews that they need to ask a supplementary question or that one or more questions are ambiguous.

Can we currently support this use case? Even if it means manually altering and re-loading spreadsheets it would be acceptable for this edge case.

But i agree it makes the majority use case more error prone.
So could we have a warning when adding a Question Use in thre context a Study if at least 1 HH has been created for that Study?
I think the correct trigger is spreadsheet *loaded* (ie HH created) rather than spreadsheet template generated, since in the latter case there's no question of invalid data in the database.

**Comment by dbrownukk** [comment]
Warning now appears on trying to create a new question usage within a Study if a Household within a Study has at least an uploaded spreadsheet status

**Comment by daiClegg** [comment]
tested OK. Good solution i think.
