### ISSUE TITLE
How do i create a new project in OIHM?

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#265]
Instance: EFD_HM

Search for Project Module returns no matches.
In Study module, New Study, Project is a drop down select from existing Projects.
But there is no opportunity to add a new project.

**Comment by dbrownukk** [comment]
All in the OX application menu setup, I now find..

Project was not in the module list for role oihm_user, though can query Projects. 

It is now set as an unrestricted module and added to oihm_user role which means it will not appear at the top level menu, only in Folder menus.

Similarly for Topics so that you can now create/modify a topic from Study/QuestionUse/Question

Similarly for Site from Study 

We can create all sorts of module, folder , CRUD action and data access restrictions, needs some planning.

**Comment by daiClegg** [comment]
Works fine as an in-flight function in Study create
Tested OK
