### ISSUE TITLE
Unable to create new WGI from WGI module - New button should be removed.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#336]
Instance:       EfD_HM
Application:  OHEA
Module:         WGI

1. Click New to create a new WGI
> Error: "Impossible to execute action: No entity found for query"

It appears the Project selection has been lost

**Comment by dbrownukk** [comment]
A WGI is created from Community / Wealthgroup module when the template spreadsheet is generated - hence the status 'Generated'

Does it make sense to create from WGI - I can remove create button.

Or, did you mean Create Wealthgroup from Community module? There was a problem there due to it still using roles, which is now not the case. 

I can create a WG in Community Module.

**Comment by daiClegg** [comment]
D'oh. Yes of course. I had forgotten the workflow is subtly different than for HHs in OIHM.
But i agree that the New button should go in WGI module.

**Comment by daiClegg** [comment]
Changed Issue title to reflect that.

**Comment by daiClegg** [comment]
** Tested OK **
