### ISSUE TITLE
Generate OHEA Spreadsheet fails to commit

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#396]
Instance: EFD_HM
App: OHEA
Project: Test #350
LZ: Berkshire
Village: Knowl Hill 
WG: #350Test WG

In Community Module, detail view, for the Village/WG above,  click on 'Generate Spreadsheet'

*Note* Spreadsheet is generated & downloaded

> Error: Impossible to execute Template spreadsheet action: Error while committing the transaction

*Note* WGI record is not created.

**Comment by dbrownukk** [comment]
Calculation of interviewees caused this. Fixed and deployed. 

Note that this deployment also includes OX upgrade to 6.2.1 - there maybe issues with a couple of layouts of 'notes', still fixing these. Otherwise looks ok and good to be on latest release (though 6.2.2 came out yesterday)

New entities Expandability Rule and Modelling Scenario now available off HM Common menu.

Testing OIHM Template creation - template is created correctly but some of the Study test data throws an error on template creation - will bug and investigate.

**Comment by daiClegg** [comment]
**Tested OK**
