### ISSUE TITLE
Unable to delete Transfers

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#405]
Instance: EFD_HM
App: OHEA
Module: WGI
Project: NIMFRU
LZ: Katakwi Fishing & Livestock Zone 
District: Katakwi
Village: Okorio
WG: Poor

1. In detail view, click Transfers tab
1. Click delete icon for first transfer

> Note the record disappears as expected

1. Click Save

> Error: Value for Unit in Transfer is required
> Error: Value for Transfer type in Transfer is required
> Error: Value for Status in Transfer is required

1. Exit the detail for this Village then return to the Transfers
> Note the deleted record is displayed.

I created further Transfers & attempted to delete them with the same result, so it does not appear to be a data problem with old inconsistent data entered before the latest change was made.

**Comment by dbrownukk** [comment]
The problem was with the isOfficial attribute. It was using default drop down combo for a boolean. Looks like a OX bug. After various trials found that you can use an alternative editor - boolean Yes/No.

Also changed the default multi row display to always display best widths rather than allow user to resize. The resize is not kept, thus is not useful (IMHO) - try it out. 

Delete of NIMFRU Poor - Transfers now works - deployed

**Comment by daiClegg** [comment]
**Tested OK**
