### ISSUE TITLE
Characteristic Resource Units 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#41]
Noticed that there is WGResourceUnit in WGCharacteristicResource and a 

ResourceSubTypeUnit in ResourceSubType 

Is the unit in resourcesubtype a default that needs to populate the Characteristic Resource Unit? 

Currently the entered Unit in Community/WealthGroup/Characteristic Resource is WGResourceUnit.

**Comment by daiClegg** [comment]
In ResourceSubType the field ResourceSubTypeKCal represents the Calorific value for the Unit (ResourceSubTypeUnit) - e.g. 1kg of Beans = 2000kCals

But in any specific project there may be a different unit commonly used, e.g. 'sack'.
There is a field (LocalUnit) in the Crops table where the actual amount produced by the WG will be recorded. And it's in the Community interview - where we find out the WG Characteristic Resources that we identify the Local Unit. That will then be defaulted into the LocalUnit for the actual Crops row when the WG interview data is loaded .
What happens now is that somebody works out the conversion (e.g 50kgs per sack), then they can work out the kCal value of the crop for any particular WG for use in the analytic reporting.
That's a use case we haven't got to yet.


But i have realised, writing this, that i've got the model wrong for this.
A local unit for a ResourceSubType (WGResourceUnit) belongs to the Community, not to a specific WG within the community. I think they would all use the same one. The way it is now, it would have to be entered for each WG. But from a programming perspective it's much easier, i think, as it is. Is that correct? If so, perhaps we should keep it as it is, and put the burden on the user for the relatively few occasions when it happens.

Btw, it strikes me that the best way to handle that conversion would be to capture the conversion rate in the WG table as an extra field (not currently modeled).
So when an interviewer enters a resource, we display the Unit (from the ResourceSubType Table) as a display only field, so the interviewer knows what the standard is and then theu only need to enter a local unit if that's not used locally.
And have an extra column in the WGCharacteristicResource table for 'Conversion Rate'.
That way if they need to enter a WGResourceUnit they can also enter the conversion unit then and there - if they know it.
Or go back later before doing the analytic reporting.

I can move this text into a new issue that specifies the Use Case & put it into a new Milestone: 'Analytics' or whatever, or you might prefer to just make the change now rather than be making UI/database changes in the Analytics Milestone.

**Comment by daiClegg** [comment]
Do we need to discuss further?

Note my text above suggests capturing local units and conversion units in the WG table -that's wrong.
Should say in the Characteristic Resources table

**Comment by daiClegg** [comment]
Further discussion with John & Celia reveals that local units can be regarded as LZ level  which is almost always Project level. Issue #101 addresses this
