### ISSUE TITLE
Unable to download attached WG Interview Spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#431]
Instance: EFD_HM (test)
App: OHEA
Module: WGI
Project Homabay Test

In detail view of any WG in this project double click the attached spreadsheet to download

> Nothing Happens

Project: Karamoja - Central Sorghum and Livestock 
District: Moroto 
Village: Namatwae 
WG: Very Poor

> This one works
> but for Cucu village in the same project, none work.

Corrupted data?

**Comment by dbrownukk** [comment]
The problem is that the record is set to non editable, thus you cannot click into any of the fields. The new Ajax file upload/download now handles this correctly. Potentially could change this so that the Spreadsheet field is always editable, but seems inconsistent to me. Just set to editable and download is simplest.

**Comment by daiClegg** [comment]
I agree, this is correct behasviour. It confused me, but anything else would be inconsistent.
