### ISSUE TITLE
Add capability to store and download visualisation spreadsheets when running a report for OIHM, OHEA and Modelling

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#461]

**Comment by dbrownukk** [comment]
![image.png](https://images.zenhubusercontent.com/5a814e994b5806bc2bc6879c/4205359d-e56c-4aab-aaa4-b2f27fb53781)
![image.png](https://images.zenhubusercontent.com/5a814e994b5806bc2bc6879c/d489da75-0423-4da6-a9a2-d619dc247e8a)

**Comment by dbrownukk** [comment]
OIHM, OHEA and Modelling Reports all now have option to download a visualisation spreadsheet if needed.

Appears underneath the selection of LZ 

i.e. ![image.png](https://images.zenhubusercontent.com/5a814e994b5806bc2bc6879c/66422415-eb4b-4707-9ebf-beb995a6fcf7)

deployed to EFD_HM only, so far

**Comment by daiClegg** [comment]
This all works.
I need to upload internally versioned & version-neutrally named files,
but the feature tested ok.

Some comments: 
1. I think the Visualisation s/sheet concertina list should be displayed closed by default because we do not expect users to need it most times they run reports
2. I was deceived by the UI at first. I ticked the visualisation spreadsheet checkbox having set up my report run, then ran the reports and was surprised no visualisation s/sheet downloaded.
I did eventually figure out i just needed to click the file (as eIsewhere in the app) to download it. So i think either the checkbox should work as i expected it or we should not have the checkbox.

thoughts?

**Comment by daiClegg** [comment]
correctly named visualisation spreadsheets uploaded for all except OHEA Coping (wip).

tweaks to UI as discussed tbd.

**Comment by dbrownukk** [comment]
Setting the frame to be closed does not seem to be doable. Will raise question on forum.

I have removed any 'action' buttons from the Visualisation Spreadsheet List

Hopefully is clearer.

![image.png](https://images.zenhubusercontent.com/5a814e994b5806bc2bc6879c/94fc01d9-b8da-48ac-872d-ef49ded5d595)

**Comment by daiClegg** [comment]
I think the change as illustrated above would remove the confusion i had about how to download.
There's visibly only one place to click - on the visualisation spreadsheet file.
But that's not deployed yet is it?

Closing the concertina on the frame, by default, is a nice to have. 
If it's not a simple setting, we can live with that. 
If somebody on the forum has a sneaky workaround - excellent.

**Comment by dbrownukk** [comment]
deployed to EFD_HM

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by daiClegg** [comment]
Seems to be an issue with the detail view of the Report module.

Instance: EFD_HM
Module: Report

1. In list view, click any visualisation report
> Detail view included the list view (not sensitive to clicks) but excludes the ability to upload a visualisation spreadsheet

![image](https://user-images.githubusercontent.com/30879677/83628976-3e29f700-a591-11ea-8b13-63c921860143.png)

**Comment by dbrownukk** [comment]
Well thats OO for you. A small sneeze and hell is let loose.

Managed to set the default list editor to assume Java would handle formatting rather than OpenXava. 

Fixed and deployed. Mote that have also set the Report data to be Read Only, other than Visualisation Spreadsheet via Admin Roles

**Comment by daiClegg** [comment]
**Tested Ok**
