### ISSUE TITLE
Should software give IHM household ID number?

### ISSUE THREAD

**Issue by stellangoleka** [dbrownukk/EFD_v2#462]
To create a new household and enter the household number:

Steps: 
IDAPS Livelihoods Production - IDAPS Livelihoods Production - OIHM - OIHM Core - Household - New - Select Study name, Enter Household name, Household Number.

For instance: 
If the household number is 12, the user will enter 12 on the household number command box. When the user clicks save, the software gives a different number eg 4. As a user, I would want to maintain the household number as indicated in the spreadsheet which is in line with the household number on the village map and the village list. 

In order to maintain the household number, I have to delete the household number given by the software and type the household number again, this time when I save, the number remains. My understanding is that the users would want to use the household number from the village household ID list.

**Comment by daiClegg** [comment]
The software generates a guaranteed unique number for the household. It needs to do this to ensure we can anonymise the data for users not allowed to see the personal data.

The user can add another number and a household name as they choose. That is stored by the software but not otherwise validated.

So in answer to your question, Yes. That is what was reuqested.

**Comment by celiapetty** [comment]
Stella has explained that  she has deleted the software-allocated number and replaced it with the field study number to facilitate data checking and potential follow up in future studies. Does  changing the automatically generated number create any problems? Should tutorials instruct users to delete the automatically generated number and replace it with the field study number?

**Comment by daiClegg** [comment]
@dbrownukk It appears you can successfully edit the HH number.
I  reproduced this :

Instance: EFD_HM
App: OIHM
Module: Household
Study:  Katakwi NIMFRU Test
HH: 68 Ateruk Hellen

The generated value was 23, i changed it to 68 successfully.
I also checked that i could not change it to a number that is not unique in the list of HH in the Study.

User-desired behaviour now appears to be that HH number is user supplied. 
We still need to enforce uniqueness - otherwise reporting is ambiguous.
If the field is mandatory on commit, but not generated that would appear to meet the user requirement.
**Is there any other implication/problem that i'm forgetting?**

**Comment by daiClegg** [comment]
@Stella @celiapetty original intended behaviour was that HH number is generated and uneditable. It isn't that anyway. Need David's input.

**Comment by dbrownukk** [comment]
Currently, as you have seen, on first save a unique, next HH number is generated. The new number is the maximum existing HH Number in the Study, +1. But, it is then editable. I suspect it should have never been editable. 

I suggest I change the HH Number field so that if a number is entered it is used, a check is always made for uniqueness. If no HH Number is entered, it is generated. The HH Number field remains editable until HH is Validated and the whole HH record is set to read only. 

Will that work? - a simple change with no impact on existing data.

**Comment by daiClegg** [comment]
@celiapetty @stellangoleka : As @David confirms, the software didn't work as i had originally intended, but it was closer to what you want than i thought, albeit needing the additional edit to the HH number.
With the change David suggests, you'll have what you want without having to do the edit separately, and we will still have a guaranteed unique HH number to help with anonymisation.
Ok?

**Comment by celiapetty** [comment]
This looks good. Stella are there any further questions at all that you would like to add.  Please could you respond so David can proceed.
Many thanks, David for the solution.

**Comment by daiClegg** [comment]
@stellangoleka, David will wait until you have confirmed before implementing, so please let him know asap. Thx.

**Comment by stellangoleka** [comment]
I suggest I change the HH Number field so that if a number is entered it is
used, that looks good to me.

a check is always made for uniqueness, that looks good to me.

 If no HH Number is entered, it is generated.

I suggest if no number is entered then, when a user clicks save the
software should give an error message like 'HH number is missing' because
all IHM households have a unique household number.

The HH Number field remains editable until HH is Validated and the whole HH
record is set to read only.

I suggest that even after validating it should be possible to set a
household number editable settings like we do with all categories. For
example after HH is validated then the user remembers that a certain item
has an error instead of entering say 7 goats the user entered 9 goats and
is able to set editable setting to correct this error and save and validate
again, so should be the household number settings.

We really appreciate if these changes can be done with no impact on
existing data.

**Comment by daiClegg** [comment]
'Set Editable' will work for the HH number, just like every other field, right @dbrownukk ?

**Comment by dbrownukk** [comment]
Yes, the set editable option will allow all of the HH related data to be updated. 

From Stella's comment above I will need to remove the auto generated HH Number completely.

**Comment by daiClegg** [comment]
As long as the presence and uniqueness of the HH number is maintained, we're fine.
I think i misunderstood the original requirement.
We were trying to limit the effort the user had to make and eliminate the possibility of user error.
Unfortunately, that now leaves us with a problem on the spreadsheet format, which for the sake of backward consistency we don't want to change.

We could suggest that if they're using a spreadsheet to load, the user encodes the HH name as: 

> "## - HH Name", 

where ## is the number the user wants to allocate and the Parse separates that into 2 fields. 
If the name field in the spreadsheet doesn't match that pattern then the Parse auto-generates the HH number & leaves the HH name as is. The user can then edit it if they choose (as now).

wdyt?

**Comment by dbrownukk** [comment]
Yes, '## - HH Name' could work in the HH Name cell of the spreadsheet.

**Comment by daiClegg** [comment]
OK, let's go with that. 

- It covers what Stella needs for direct inputting.
- It supports spreadsheet loading.
- It doesn't affect backward compatibility.
- It's a low risk change.

**Comment by dbrownukk** [comment]
Some Implementation Notes:

HHNumber within Study remains unique but is not necessarily a complete sequence  i.e. HHNumbers could be  1,2,4,6,7

On Save of NEW Household, if HHNumber is blank it will be given the highest HHNumber, within Study +1.

If you edit an existing HHNumber it can be used, as long as it is still Unique.

On parse of spreadsheet, if the HH Name begins with a Number and a dash, then the number will be used for eth HHNUmber

ie.

HHName = 123 - Dave's House

The parse routine looks for the "-" and uses the number before the "-" i.e. HHNumber is set to 123
Number is limited to maximum of 3 numerics

The following will parse 

1 - HHName
12 - HHName
123 - HHName

to be deployed

**Comment by dbrownukk** [comment]
Deployed to EFD_HM

**Comment by daiClegg** [comment]
Tested the HH number embedded in the HH name - works correctly if the HH of that number exists and if it doesn't.
Tested editing the generated HH number - works correctly retaining uniqueness.


Study: A Study
HH: 30

Created a new HH, uploaded a SS with a HH name that had no embedded  HH number (attached)

`ERROR` - Impossible to execute Parse Interview Spreadsheet action: For input string: "Bernard Blac"

[M2TutorialTestHH10.xlsx](https://github.com/dbrownukk/EFD_v2/files/4684741/M2TutorialTestHH10.xlsx)

**Comment by dbrownukk** [comment]
Assume the new Household had not been saved at this point. Checking this..

**Comment by daiClegg** [comment]
I got the warning about the different study and ignored it - we agreed that was ok.
But we hadn't thought of the implications for customisation questions & answers.
If we stop parse they have to go back to the spreadsheet and correct the questions and answers there, by hand. 
If we allow parse but ignore the Q&As, they could add the correct data in the app.
But this is extra work, with further implications for Validate, just to support a very exceptional situation that could be fixed anyway by editing the spreadsheet (Summary & Q&A tabs) so it looks like it was generated from the correct Study, couldn't it?

If i'm right here, i vote for halting the parse with a helpful message ('Q&As not consistent with current Study' or some such).

wdyt?

**Comment by daiClegg** [comment]
btw, should this move to a new issue?

**Comment by dbrownukk** [comment]
Agree. I think the spreadsheet template for a Study should be used. The implications on Question Config / Questions and Answers is horrid. The flexibility given via Configurable Questions does have a price..  I will update to check and stop if not current Study, which gives an understandable rule rather than discussing Questions sets.

**Comment by dbrownukk** [comment]
New Issue? - no, easy to finish here and has the complete trail

**Comment by dbrownukk** [comment]
Now checks that Study in Hosuehold Module is the same as that in the spreadsheet.

Note that Study "Katakwi- NIMFRU Test" seems to have 2 flavours. One with a space after Katakwi and one without before the hyphen - might cause confusion, did for me..

deployed

**Comment by daiClegg** [comment]
INstance: EFD_HM
App: OIHM
Module: HH
Study: A Study

1. Click New
1. Select 'study  'A Study'
1. Upload spreadsheet 'OldMotherRiley.xls'
1. Click Save.
> note HH number is generated
5. ClickParse Interview Spreadsheet
> Fails 'HH number must be unique within study'
> Displays a blank record 

This is because the Spreadsheet encodes the HH number in the HH name field as 27. 
But HH 27 already exists.

I think parse should 

- ignore the encoded HH number
- keep the generated HH number.
- set HH name field as in the spreadsheet
- display a warning message 'Encoded Household number already exists'
- leave it to the user to sort it out by editing HH numbers as they see fit.

wdyt?

**Comment by dbrownukk** [comment]
On creating NEW Household the HH Number is set to the next highest  HH Number within the Study
On parsing a spreadsheet, it will attempt to extract a HH Number from the first 3 characters of the HH Name. If HH Number within HHName is equal to current module HHNumber then parse will continue.

If this is a duplicate, of an existing HH then the parse will fail. Go back and edit the spreadsheet to either:-
1. Remove HH Number from HH Name in spreadsheet
2. Change the HH with the duplicate numer to something else, within the HH Module
3. Change the HHName within the spreadsheet to include a new, unused number.

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by daiClegg** [comment]
Not yet deployed to the Production Instance
