### ISSUE TITLE
Unable to upload interview spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#468]
Instance: EFD_HM
App: OIHM
Module: HH
HH: Old Mother Riley

1. in Module Study, click 'AnOIHM Study' to invoke detail
1. Click 'Template Spreadsheet' to generate interview spreadsheet template view
1. Fill in the template (see attached)
1. In HH module, click 'New' to create a new HH
1. Upload the filled in Template spreadsheet.
1. Click Save; uploaded spreadsheet saves successfully
1. Click Parse Spreadsheet
`ERROR`      Parse Failed - Wrong template for Household Members java.lang.NullPointerException
`ERROR`        Cannot Validate Household, No Assets to Validate

**Comment by dbrownukk** [comment]
Can you add populated spreadsheet

**Comment by daiClegg** [comment]
Sorry, it is attached to one of the HHs i created in this Study (27, 28, 29) for testing, along with another that was originallygenerated for another Study - which is why i went back to the beginning to create this one:


[OldMotherRiley.xlsx](https://github.com/dbrownukk/EFD_v2/files/4689056/OldMotherRiley.xlsx)

**Comment by dbrownukk** [comment]
After convincing myself all the OX libraries had been updated for processing Excel files it finally dawned on me that this is an XLSX file not XLS. Hence the problem.  The file format, handled within teh Java libraries is different. XLS uses HSSF libraries, XLSX uses XSSF. However, will introduce a check on parse so that I do not go down this hole again..

If there is a requirement for XLSX this will be a chunk of work.

Also, found an issue with HH Member numbering and fixed a couple of other issues I saw.

Not deployed

**Comment by daiClegg** [comment]
No rest for calc. Except by GitHub. It won’t allow attach or xls files to issues. I’ve been converting to upload for a while now.

**Comment by dbrownukk** [comment]
Aha. Anyway, now have check in parese to ensure the spreadsheet is, as generated, an xls file. 

deployed

**Comment by daiClegg** [comment]
**Tested OK**
