### ISSUE TITLE
(OIHM) Modelling - Expandability Rule applied incorrectly to Food Transfers - Food Income

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#581]
Instance: QA
App: OIHM Modelling
Change Scenario: Katakwi - OIHM
HH: 91

1. In the HH module, detailed view of the above HH in Anyangabella, Click Set Updatable
2. In Transfers Tab, Set Amount Sold for 'Groundnuts, dry' to 5kg.
3. Save & Validate
4. As per #566, run Coping strategy for the above Change Scenario & HH
5. Open the downloaded data extract & navigate to Cash Income.
> Note the change in Cash income reflect accurately the additional sale of 5kgs of 'Groundnuts, dry'
6. Navigate to Food Income Tab
> Note there is not loss of feed income from the 5 Kgs of groundnuts that have been sold

Either Food Transfers are not included in Food Income (i've not tested that yet); they should be.
Or Expandability rule effect on Food Transfers is not effected; it should be.

See also #566

**Comment by dbrownukk** [comment]
Review, document calculation and correct

**Comment by dbrownukk** [comment]
Modelling report - Food Income now reduces the amount for Food Transfers and Cash Amount, as was, does increase if Food item is in Expandability Rule.

For 

App: OIHM MOdelling
Change Scenario: Katakwi - OIHM
HH: 91

I set Transferred Amount of Groundnuts dry to be 20 rather than 10. The 10 'Consumed' are then sold and a reduction is made in Food Income KCals

Deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
Phew. That took some thinking through.
But it works!

**Tested Ok**

**Comment by dbrownukk** [comment]
Deployed to QA and Prod
