### ISSUE TITLE
OIHM reference year : not enough space to add start and finish months

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#599]
There should be space to include the start and finish dates of the reference year eg 01/06/2018-31/05/2019. If this involves too many digits, month/year is acceptable.

**Comment by celiapetty** [comment]
For consistency might the OIHM reference year set up (current version attached) be configured in the same way as the OHEA set up (current version attached) ie scrap the Reference year Box in OIHM but keep the Reference year heading on top of the start and end  date calendars?
![OHEA date set up](https://user-images.githubusercontent.com/44376631/109854479-000c5180-7c4f-11eb-839d-040efe6a07c2.PNG)
![IHM date set up](https://user-images.githubusercontent.com/44376631/109854538-131f2180-7c4f-11eb-8557-5a052451693f.PNG)

**Comment by daiClegg** [comment]
I'm content with that.

But should not the Start & End Dates be on the Project, not Community/Village in OHEA?
And on the Study in OIHM, Right?

**Comment by celiapetty** [comment]
That's correct: Reference year start and end dates should be at Project level for OHEA and Study level for OIHM

For some reason these messages always go into my Spam folder hence a couple of days delay in replying....

**Comment by daiClegg** [comment]
I've written up this in #598 for OHEA.
To confirm, this implementation:

![image](https://user-images.githubusercontent.com/30879677/110376780-81972180-804b-11eb-9a9b-170316b442bf.png)

... is the required implementation for OIHM, but at the Study record, not Project, so the Project field in this screenshot is not required.

**Comment by dbrownukk** [comment]
review and fix

**Comment by dbrownukk** [comment]
Removed start date and end date from Community.

Added ReferenceYear and EndDate to Project

Visible as above in Project, but not quite like above in Community. The drop down pick list of Project has Reference Year, Start Date and End Date below (OX Limitation). Note that the values from Project are not synchronised until Save. An Edit of Project from Community does synch.

**Comment by celiapetty** [comment]
No-the box doesn't allow you to give the reference year which typically
spans 2 calendar years eg 2017-18. (it didn't when I tried this). Reading
back over the thread, it looked as if this wasn't desirable (from a
programming perspective?) so I suggested drop the reference year box if,
OHEA and OIHM both have the reference year start date and reference year
end date indicated in the 2 calendars  (written up as issues) /.Does that
make sense? Let me know if  we need a call to clarify .

**Comment by daiClegg** [comment]
Celia, on 17th february you wrote (in respinse to my comment of 16th February)

> Completely agree with Dai's suggestion. The reference year 2017-18 is not relevant if we have the Reference Year Start and Reference Year end.
To capture when the field work was done for clarity we should add Field study start and Field study end

Are you now saying that's not right?

**Comment by daiClegg** [comment]
I thought we had discussed and agreed that adding start and end dates (presumably meaning Survey start and end dates) would be the same for all the Communities in a Project (right now Project only allows one Survey - see #644) because they relate to when the Survey (for the project) was done.

When #644 is implemented (it is currently a candidate for the next sprint) i would expect to have the same dates on an HEA Study as on an IHM study

My feeling now is that we need, at the Study level (IHM or HEA - assuming #644):

- Reference Year (for the survey - ie what agricultural year is being surveyed in this Study
> *Implementation Note* i think this would be best laid out as a 4 digit, editable numeric field followed by " - "  and then a 2 digit read-only numeric filed with generated content to be the last 2 digits entered in the previous field +1, modulo 100. The user then enters a year (say '2018' and the next field contains '19' so the whole thing reads' 'Reference Year 2018 - 19".
- Survey Start Date - as Start Date now, just changing the prompt
- Survey End Date - As End Date now,  just changing the prompt

We should also remove Reference Year (that now devolves the Study level) and End Date (as per the comment above re uploaded documents) from the Project module.
I am going to suggest we keep the start date because that will support displaying projects by Start Date. In future when we might have many projects, being able to see the recent ones first would be helpful.
And it is hard to think of a situation where a user is creating a project in IDAPs but the project doesn't exist already (ie has started) in the real world.

I am now going to close this issue and request any future discussion takes place in #644 
I will copy all my most recent notes here to that issue.
