### ISSUE TITLE
OHEA/Modelling: Change Scenario calculation not as expected.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#623]
Instance: Testing
App: OHEA/Modelling
Change Scenario: Mukono -Sweet Potato total loss
LZ: Mukono, Banana Coffee, Piggery 
District: Mukono 
Villlage: Bugoye 
WG: Middle

1. Invoke WGI module for this WG, detail view
>   Note that they sell 980kgs of Sweet Potato, dry for 232.2/kg, and consume 1050kgs
2. In Livelihoods Modelling module select the change scenario above.
> Note the only Price Yield entry for this Change Scenario is Sweet Potato, dry, Yield - 0% Price = 300%
3. Run the Change Scenario for the village above
4. Open the downloaded modelling data extract
> Note the Cash income for the WG has increased by exactly twice the original cash income due from Sweet Potato, dry,
> That is not what i would expect. I would expect a loss of cash income (none to sell)
> Note the Food Income has not changed.
> That is not what i would expect since that WG consumes Sweet Potato, dry.

annotated data extract attached.

[ChangeHyCRISTALMon Apr 12 19_17_39 UTC 2021.xlsx](https://github.com/dbrownukk/EFD_v2/files/6299408/ChangeHyCRISTALMon.Apr.12.19_17_39.UTC.2021.xlsx)

**Comment by dbrownukk** [comment]
A "0" Yield outlier...   Agree, Cash Income increase is wrong.

Fixed, but a question:-

Struggling with the concept of 0 yield and a price change of 300% How does price change affect anything? 

Not deployed.

**Comment by daiClegg** [comment]
A crop might fail completely,  locally but still be available in the market at an inflated price.
It would be irrelevant except if that crop was part of the default diet that people would normally buy to supplement their own production.
It might be a realistic scenario if the crop is normally grown only by Middle or Better Off WGs but bought & consumed by the Poor WG.

**Comment by dbrownukk** [comment]
Cash now correct but have issue with Food Income, or rather Yield change and Food Income

You mentioned above

_Note the Food Income has not changed.
That is not what i would expect since that WG consumes Sweet Potato, dry._

I agree that the Food Income should change, but I see that the calculation uses the new Yield as the multiplier for Units Produced, Sold, OtherUse and Consumed (calculated based on Produced,Sold, OtherUse).

In this case Yield is 0. Thus Units Produced, Sold and Other Use are all zero, resulting in no Food Income increase.

Should Yield be used to calculate post Yield/Price variation values for Produced, Other Use and Sold units?

Perhaps too close to this and need to sit back a moment....

**Comment by dbrownukk** [comment]
Cash and Food Income changes now appear correct.

Deployed IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
The changes in food i come and cash income are now exactly as i calculated them:
CI down by 980 * 232.2
FI down by 1050 * 3330

**Tested Ok**

**Comment by dbrownukk** [comment]
Deployed to QA and Prod
