### ISSUE TITLE
OIHM: Multiple error messages creating a new HH

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#627]
Instance: Testing
App: OIHM
Module: Household

1.  In HH module, click New

Note displays with multiple occurrences of 
> "Impossible to execute action: null"

**Comment by dbrownukk** [comment]
So much for that unit test... said it had passed, but clearly not. rewriting test.

Issue was with new Local Unit behaviour, was not setting a default value.

Fixed, deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
The place where i got that error before now works (ie New)

But now some further steps will cause me to encounter the same error message:

Instance: Testing
App: OIHM
Module: Household

1. In HH module, click New
2. Select a Study from the drop-down
3. Click Save
4. In the Crops tab, click Name drop-down
5. Start to Type 'Maize'
6. Select "Maize, Dry Kg"
> "Impossible to execute action: null"

**Comment by daiClegg** [comment]
By scrolling down the drop-down i can successfully create a Crop record for "Maize, dry" (and get Ox Cart as the unit - yay)

**Comment by dbrownukk** [comment]
Unusually, feels like an OX bug. Hitting 'Enter' with an invalid value in the field, rather than scrolling and selecting with Mouse, fires the on change trigger with invalid data for the RST. This, plus the Study, Site, LZ are used to possibly find a Local Unit. 

I think validation should be done before firing on change trigger. 

Anyway, coded around. If you hit Enter the default 'Save' is executed which will result in a sensible error message(s) based on validation of the Crop (or other asset/resource)

If you use the mouse to select value the problem will not have appeared, but this is an accessibility issue. You should be able to type in and hit return. 

The default for 'Return/Enter' in any OX screen is to Save the current record. We could change this, but a big change in behaviour if you are used to this. 

Deployed IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
Agree about the Save behaviour. Leave the default as is
I have a tendency to use it inadvertently, but that's my problem.

If this is an OX problem, it will manifest all over the apps won't it?
I'm going to make a habit of using this approach (ie not using scroll for search) to look for any more instances.

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by dbrownukk** [comment]
Deployed to QA and Prod
