### ISSUE TITLE
Communities missing in livelihood scenario model 

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#629]
Instance QA
OHEA
Livelihoods modelling
Mukono Sweet Potato loss Heather 12/04/21
Mukono Banana Coffee piggery
Price Yield variation as shown (yield 1 price 300)
Select report
Only 4 out of 7 communities for which data has been recorded appear in the report
Note: 
Select OHEA  Core
Project: Mukono Banana coffee piggery
Select Report
7 communities appear
Select Livelihoods HEA
Report for all 7 communities is generated

**Comment by daiClegg** [comment]
A village is only included in a model if there are 3 validated WGs
You cannot validate a WG interview dataset if no data is included.

That's why these villages are excluded.
The workaround is to just give the WG 1kg of 1 crop sold for 1 currency unit and then validate the record.
Modelling will then include the village.


Note that if the WG family group size is not specified the model will calculate the KCa;l requirement as zero, so this is a required piece of data.

**Comment by daiClegg** [comment]
Is that workaround sufficient?
If so i will close the issue.

**Comment by celiapetty** [comment]
Will give it another try. I wasn't able to get this to work yesterday but
hadn't included a WG family size.

**Comment by celiapetty** [comment]
OK- works, thanks. You need to include an asset ie land for crop. Just missing Lusela now as a WG hasn't been generated and data looks  poor so will leave this for now.

**Comment by daiClegg** [comment]
Will test that Land without any Cash or Food Income generating resources will do the trick.
That seems to me a better workaround

**Comment by daiClegg** [comment]
Just adding an Asset (Land) has been tested successfully (by @celiapetty)
 
Need 3 validated WGs for a Village to be included in the modelling reports.
If no data exists for one, an empty WGI record with just a single Asset defined will allow the WGI to be validated.

Note that the WG data: # memers of family unit, order of WG (1,2 or 3) %in WG should be supplied to allow calculations to be made correctly.
