### ISSUE TITLE
Change Scenario of Transfers does not deliver expected result

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#649]
Instance: Testing
App: Modelling/OIHM
Change Scenario: Test Extent of Variations
Study: Katakwi - NIMFRU - AIHM 2018

HH12:

Transfer change not as expected
The transfer price/yield change is for 'other goods' - ie not a cash or food transfer.
But this HH only has Food transfers
so should have had no impact

However, it does raise the question of how to know what "Other Goods" RST is affected.
The Price/Yield Variation edit popup does not allow the user to specify what RST is being transferred.
For example 'Cooking Oil'.
There is the methodological question as to whether it is ever likely to happen, but if we treat other goods transfers like food transfers and specify the RST then the UI is no more complex and the model is consistent, even if no-one would ever use it in the real world. (will pursue that separately)

Equally it is not possible to specify what currency is being transferred in a Cash Transfer. Arguably there is no functionality lost if this is constrained to be the project currency.

**Comment by dbrownukk** [comment]
In this case Wild Food Mango is a Transfer in HH12. It is also listed as a Price Yield Variation 70/120

Open to debate I suispect.

If a Food Type is transferred and yet at the same time is subject to a Price Yield variation should not the new price and yield take effect. Otherwise you will be selling the same food at diifferent prices.

Remove the Mango price / yield variation and Transfer CI is unchanged on processing Change Scenario

**Comment by daiClegg** [comment]
That explains why i saw what i saw.

Wrt the issue raised (transfer of a food type affected by the Change Scenario), In a conversation i had with Celia, she did say that transfers are not affected by a yield change, because it would usually be from out of the LZ via government, NGO or family. 
But, if the transfer is sold, and the local market price has changed surely that must take effect?

I think this is one to be resolved in User Testing.
