### ISSUE TITLE
OIHM: Study module allows Site to be in any LZ, regardless of whether that LZ is associated with the Project 

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#656]
Instance QA
OIHM Core
Project Chitipa
District Chitipa
LZ Chitipa Livestock rice and livestock zone
Generate report, report spec Disaggregated Food sources
Worksheet Custom report spec Correctly identifies the study name
Worksheet Disaggregated Food Source by household, incorrectly identifies the LZ name. Here, rather than the LZ name allocated by DC  (Chitipa Cassava Rice and  Livestock)  LZ name Karonga, Crop and Livestock appears.
Note-I can sort out correct LZ designation from FEWSNET map (I think it's Chitipa Millet and maize) in due course.
A similar bug was noted for Wamala. I created a new LZ for this project (LZ missing):  Mityana, Wamala lakeshore.
Generated a Disaggregated Food sources report as above. 
Correct Study named on Custom report spec :Mityana-HyCRISTAL-Wamala lakeshore 2015. LZ shown on Disaggregated Food source by household incorrectly shown as Homa Bay Lakeshore
NOTE: Chilimba does show the correct LZ on the disaggregated food source worksheet.

**Comment by daiClegg** [comment]
This Study is in the "MA4 Chitipa" Project.
The Project only has one LZ, which is "Karonga, Crop&Livestock"
This is the LZ that the Report picks up.

However, the Study Site is the Village "MK", which is in the LZ "Chitipa, Cassava,Rice&Livestock Zone"

Clearly, the behaviour is not correct but i need to think through what is the correct behaviour.

tbd.

**Comment by daiClegg** [comment]
In the Testing instance, it is not possible to add a Site to a Study that is not in a LZ already associated with the Project that ocntains that study.
I think this is correct behaviour.
If the user has to back out and return to Project to add the relevant LZ,  that's a slight hassle, but in the real world, they'd have set up the Project with its LZ(s) anyway, so it would be exceptional so i don't think we want to allow adding LZs to the Project  in the Study module. 
However in the example here - in the Producitn instance. That appears to have been done - by me!.
I need to re-test that.

**Comment by daiClegg** [comment]
IN Productin, if you add a a Site to a Study, you can only doo iit by picklist, and the list offered is only the sites in LZs in the Project. That appears to be correct.
However, if you type any valid Dstrict name in the District field of rthe LZ frame of the Study model, it wil allow you to edit the site to be in the District, regardless of whether the District is in an LZ assocuated with the Project.
That's not correct behaviour.


No conclusions yet; i'm still testing and just making my notes here

**Comment by celiapetty** [comment]
For information: the Disaggregated Food Source by household is picking up the correct project data: cross checked HH 1 Chitipa and HH6 Wamala, Mityana lakeshore. In both cases, the correct crops were listed

**Comment by daiClegg** [comment]
So now i think i know what's going on and this is what i propose to do about it:

1. Re-focus this issue to be about disallowing eidt of the District field inthe Site of a Study. 
2. Raise a new issue, referencing this, requesting that the Dissagregated food Sources report takes its LZ from the Site of the Study 
3. Fix Chitipa in QA & Production instances so that user testing can continue.

**Comment by daiClegg** [comment]
> 3. Fix Chitipa in QA & Production instances so that user testing can continue.

fixed, the data but the wrong LZ will be in the report until item 2. above is fixed

**Comment by daiClegg** [comment]
The change of behaviour required is: 

- Prohibit typing into the District field in the Site frame of the Stidy module.
- Only allow the Site of a Study to be populated by selecting a Site in a LZ already associated with the Project containing the Study.

**Comment by dbrownukk** [comment]
You have to have at least 1 editable field, otherwise treated as Read Only, which is not what we want. Set Site to be non modifiable, but allowing new Sites to be created, otherwise no sensible place to create a Site other than off the Site menu. 

If you try and edit the District name and Save then a warning appears (not trapped yet, just says Impossible to Save..) and displays any valid LZs belonging to Project in Study. You can also create a new Site belonging to any valid LZs in Project in Study. 

Deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**

@Celia, note this means it's fixed and is available in my testing instance.
It will be fixed in QA & Production next time David refreshes them, which we generally only schedule when there is a bunch of fixes/enhancements.

**Comment by daiClegg** [comment]
Instance: Testing
App: OIHM
Module: Study
Project: Test LZs in OIHM Studies
Study: Test LZs in OIHM

1. In Detail view of Study "Test LZs in OIHM"
> note no Site is recorded
> note the Project is "Test LZs in  OIHM Studies"
2. In Detail view of Project "Test LZs in  OIHM Studies"
> note this Project includes 2 LZs: "Ox Cart Using Locality" & "Testing LZs in OIHM"
3. In Detail view of Study "Test LZs in OIHM", in District field type "Berkshire"
4. Hit return
>  the Site is correctly populated with the only village in "Berkshire", which is the only District in the LZ "Testing LZs in OIHM"
*Expected behaviour*
5. in District field type "Ox McOx Cart"
> the Site is populated with the first village in "Ox McOx Cart", which is the only District in the LZ "Ox Cart Using Locality"
But there are 2 villages in that District, and get no option to select the other.
*Not expected Behaviour*
6. in District field type "Katakwi"
> the Site is populated with the first village in "Katakwi", which is in an LZ not included in this Project
*Not expected Behaviour*
7. in District field type "XXX"
> Error message and pop up select list f all Sites in all the LZs in the Project. 
*Delightful Behaviour*

**Comment by daiClegg** [comment]
Re did test sequence (numbered as above)

3. (4.) In Detail view of Study "Test LZs in OIHM", in District field type "Berkshire" Hit return
>the Site is correctly populated with the only village in "Berkshire", which is the only District in the LZ "Testing LZs in OIHM"
Expected behaviour

5. in District field type "Ox McOx Cart"
>Popped list of available villages in the Project with error message : 
`District Not Found or not Unique, Select from List or use Search button`
Expected Behaviour

6. in District field type "Katakwi"
> error message : 
`District Not Found or not Unique, Select from List or use Search button`
Expected Behaviour

7. in District field type "XXX"
>Popped list of available villages in the Project with error message : 
`District Not Found or not Unique, Select from List or use Search button`
Expected Behaviour



now to test as expected...

**Comment by daiClegg** [comment]
8. District field type click Search
>Popped list of available villages in the Project
Expected Behaviour

**Tested Ok**
