### ISSUE TITLE
Cannot create a new LZ from within Project module

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#67]
In Project module, list view pick any project.
Detail view pops up.
click New  LZ,
provide a new LZ name and country.
Click Save.
Page refreshes, but gives no message and does not exit the dialog.
Click close to exit and confirm the LZ has not been created

**Comment by daiClegg** [comment]
I thought this might be a duplicate of Issue #54.
So i tried resizing the font in the window, up and down to see if there was an invisible message.
If there is i can't find it.

**Comment by dbrownukk** [comment]
this is problem with create manytomany - must use
@NewAction(ManyToMany.new) due to a bug..

However, this fix forces the use of default view for LZ which includes Site. Project must be saved before adding LZ and a Site. Went around in circles trying to force the use of a non default View to avoid this but this is best solution for the moment..

**Comment by daiClegg** [comment]
Tested OK
