### ISSUE TITLE
Provide visual summary of Food Expenditure, by Resource SubType,  by Wealth Group

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#95]

**Comment by daiClegg** [comment]
Basis is Food Purchases

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
Project: Mukono - new test
LZ: Banana Coffee Piggery 
District: Mukono 
SubDistrict: Butere

Tested very fine indeed, so far.
Tested download OK (pdf only)

Normalised version not yet available. so leaving open.
And need  to do furthert tests (more WGs. more purchases & no purchases in some WGs

**Comment by daiClegg** [comment]
Found a very interesting"Feature": after validation, you can change the resource sub-type for an entered resource and it is accepted and reflected in the report.

I suspect this is not intended but is it acceptable. For example, i changed "Tangawizi" to "Ginger".
They are both in the database, as synonyms. So it is semantically correct. But is it a bit dubious?
I think i will consult my domain experts on this one.

**Comment by dbrownukk** [comment]
As part of the validation we could set various fields to be non update-able getView().setEditable("propertyName",false);

In which case, we should set all validated wealthgroup details to be non updateable. To update you would reset the WGI status to anything other than 'Validated' and then go to a resource item and set line status to Invalid so that it can be edited. 

Lets await discussion

**Comment by daiClegg** [comment]
Re-seting from Validated to Parse to unlock would then make it a deliberate action. 
That would eliminate any accidental editing.

Sounds like a good resolution. I will propose it.

**Comment by daiClegg** [comment]
Moved this to its own issue: #142,since it is not specific to this report.

Otherwise Tested ok
